### ISSUE TITLE
Add Sending custom Txs 

### ISSUE THREAD

**Issue by ProjXDev** [idena-dev/idena-pocket#19]
Hi , There is a payload for each tx made why don't we use it in a nice way to send messages? on chain? so it be like Crypto mail 
We can send up to 1024 byte text in each tx to any address .If You can create a database with usernames ? se we search by username for the recipient and retrieve its address and send the message with the lowest fee :) this is a great idea for on chain mail service And also you should make a loop in old txs to see if any one has  payload wich is not 0x and display it as a mail , thanks

**Comment by menxit** [comment]
This is a great idea, but I think it should be an external Dapp. This, will help to use idena-pocket to create something similar.
