### ISSUE TITLE
Update wallet balance and transaction list in real-time for incoming transactions

### ISSUE THREAD

**Issue by bingbinglee** [idena-dev/idena-pocket#2]
How to reproduce
1. Login to a idena-pocket wallet
2. Send DNA to the wallet

Desired behavior: 
1. Wallet balance update in real-time when the transaction is received.
2. Transaction list in update real-time when the transaction is received.

Current behavior:
1. Wallet balance does not update unless you logout and log back in.
2. Transaction list does not update unless you logout and log back in.

**Comment by bingbinglee** [comment]
@menxit @idenadev

**Comment by menxit** [comment]
I added it in frontend v2 roadmap.
