### ISSUE TITLE
Skip seed confirmation with reminder

### ISSUE THREAD

**Issue by ProjXDev** [idena-dev/idena-pocket#23]
Why i have to type the words i have chosen ? i know that is a layer of secure 
but many lazy people will like a skip button and maybe a reminder to backup the mnemonic will be good :)

**Comment by menxit** [comment]
Skip of confirmation with reminder seems great solution. I labeling this issue as enhancement. It's not a priority, but I'd love to see this implemented.

**Comment by bingbinglee** [comment]
This is a standard UX protocol across all wallets today and makes sure you really stored your seed away. same way you have to type your password twice to confirm it :) 
I do not think this can be made optional.

**Comment by menxit** [comment]
Yes, as usual something to skip this procedure could be a great solution from a nerd perspective, but it could be fatal from an UX perspective. In @bingbinglee I trust, I prefer not to introduce this change.
