### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ProjXDev** [idena-dev/idena-pocket#24]
A way to translate the wallet in other languages will be helpful  so all idena users can use the wallet

**Comment by menxit** [comment]
Uh! Localization it's something I'd like to avoid, but I know it could be a great improvement from a UX point of view. If someone want to implement this is welcome!

**Comment by bingbinglee** [comment]
I can attempt this.

**Comment by menxit** [comment]
I'm thinking that localization is something that introduce a lot of complexity in code and that we will must to maintain on new features released.

I'd like to use something like [localizejs.com](https://localizejs.com/). [It doesn't require to change code ](https://help.localizejs.com/docs/library-api) and offers an easy control panel to manage translations. However it costs a lot ($50/month, 2 languages and $275/month 5 languages). Do you know similar services but less expensive?

I don't want anyone wasting time in something that can be replaced by a service.

**Comment by idenatoday** [comment]
poeditor.com is free for open source projects and works great.
Collaborative i18n, comments, exports as po/mo but also js or other formats.

**Comment by menxit** [comment]
Wow, great service! [It seems requires more effort than localizejs](https://medium.com/worldsensing-techblog/i18n-with-react-react-intl-and-poeditor-d21a8ecc8e8e), but it could be a good compromise.

**Comment by bingbinglee** [comment]
@menxit popeditor and i18n are almost similar in a way that they have similar level of complexity. popeditor lets to manage translations separately (and insert translations into the project during build) I guess from what i could sense from the glimpse of the blog, while i18n maintains a handmade collection of locale json inside the app directory which you can manually add to. 

i18n seemed pretty okay since the main project also relies on the same for translations.

**Comment by menxit** [comment]
Uh, you are right. I thought poeditor let to update translations avoiding building process. Yep, I can confirm that this would be unuseful :/

**Comment by bingbinglee** [comment]
@menxit this work is done and **en**, **hi** translations are added in the PR to demonstrate how it works. 
https://github.com/idena-dev/idena-pocket/pull/29
Have a look when you can.

@ProjXDev if you would like to do Arabic translation, all translation files would be available in /public/locales/

**Comment by ProjXDev** [comment]
Hey i will do it soon when i get some free time 😀
