### ISSUE TITLE
Enhance idena-pocket availability

### ISSUE THREAD

**Issue by menxit** [idena-dev/idena-pocket#37]
I'm opening this issue to describe the idena-pocket outage of May 30th, 2020 and to discuss how to avoid similar events in future.

## How idena-pocket works
When you send a transaction or you retrieve your balance on idena-pocket, you interact with Idena network. To achieve this result, idena-dev created [idena-rpc](https://github.com/idena-dev/idena-rpc); idena-rpc it's a proxy that lets to open only non critical endpoints; a list of opened endpoints it's available [here](https://www.idena.dev/idena-rpc/introduction); idena-rpc is provided of a mechanism such that on crash, it come back online automatically. As a proxy, idena-rpc forwards its request to an idena node, managed by idena-dev team; idena node is not provided of mechanism to automatically restart on crash.

![idena-pocket](https://i.ibb.co/zQpFkGc/idena-pocket.png)

## What happened
On May 30th, 2020, due [an idena network bug](https://medium.com/idena/may-30-2020-idena-validation-incident-report-e1c8ebd56ded), most of idena nodes crashed, included the idena-dev managed one. When a member of team returned available, it was manually restarted, causing an outage of ~8 hours.

## Quick and dirty fix to enhance idena-pocket availability
As a temporary fix, I restarted the node using this bash script. It runs the idena node process inside an infinite loop. On node crash, it is restarted. It should limits outage due unexpected idena node crash.
```bash
#!/bin/sh
RC=1
while [ $RC -ne 0 ]; do
        idena --config=./config.json --port=40405 --rpcport=9009 --datadir=./datadir
        RC=$?
done
```

## Proposed solutions
- [X]  **systemd**: we could replace the quick bash hotfix with a process manager like systemd; in particular the `Restart=on-failure` option seems good four our needs. [DONE](https://www.idena.dev/idena-rpc/run-idena-as-systemd-service)
- [X] **health endpoint on idena-rpc**: [this endpoint](https://rpc.idena.dev/health) will be useful to check if public idena node is synced and up and running. [Thread about how it is implemented](https://github.com/idena-dev/idena-rpc/issues/2).
- [X] **status idena-rpc status page**: created a dedicated page to monitor idena public rpc status [https://status.idena.dev](https://status.idena.dev)
- [X] **idena-pocket show rpc status**
![idena-pocket-status](https://i.ibb.co/CmbphY0/Schermata-2020-05-31-alle-6-48-23-PM.png)

**Comment by bingbinglee** [comment]
systemd seems a more cleaner less manual process which will have minimal impact on user experience. 

custom rpc will provide more flexibility but is prone to user errors - meant for advanced technical users.

**Comment by bingbinglee** [comment]
Another option:

Possibly maintain multiple nodes behind idena-rpc in form of a load balancer which can pass off requests to distribute incoming traffic to the rpc endpoint. 

Also, in case of one node failure - it can fall back to the ones which are still alive reducing a single-point-of-failure scenario.

**Comment by menxit** [comment]
> Possibly maintain multiple nodes behind idena-rpc in form of a load balancer which can pass off requests to distribute incoming traffic to the rpc endpoint.

This is absolutely something we should implement. However due limited funds, I prefer to delay use of a load balancer and multiple idena node instances.

Meanwhile I can customize a good systemd configuration to limit as possible outages.

**Comment by bingbinglee** [comment]
WOW love it!! great job as always!
