### ISSUE TITLE
Show ui loading indicator while logging in

### ISSUE THREAD

**Issue by bingbinglee** [idena-dev/idena-pocket#6]
Today, when you press the login button - there is no UI feedback i.e. loading indicator that processes are firing in the background (pulling in txs, balance, price, etc), which looks like it is stuck on the UI. 
A loading indicator or a toast similar to when you send a transaction that shows the login process is in progress will be helpful. Right now there is a couple of seconds delay to that process.

**Comment by bingbinglee** [comment]
DAMN SON!

**Comment by menxit** [comment]
flow of consciousness
