### ISSUE TITLE
Last character from optional message is omitted

### ISSUE THREAD

**Issue by bingbinglee** [idena-dev/idena-pocket#8]
Message in this transaction
"test send"

Message in the wallet
"test sen"

<img width="503" alt="Screen Shot 2020-04-18 at 12 03 57 PM" src="https://user-images.githubusercontent.com/62775041/79642652-e06e5680-816c-11ea-81c9-523ab245ab24.png">

**Comment by menxit** [comment]
I included this bug fix in frontend-v2 branch.
